### PR TITLE
Fix for training on latest version

### PR DESCRIPTION
**Pull request by utkarsh530**
The current code does not work with Julia 1.9 + the latest version of the packages. Adding compats might help.

Moreover, after fixing the code, I cannot get the training to work:

https://pastebin.com/2cAJbbzZ

### CODE REVIEW

**Comment by YichengDWu** [comment]
Thank you, I have been waiting for https://github.com/JuliaDiff/ChainRules.jl/issues/645 to be fixed for a while. Before that, training on GPU is quite slow. Maybe you would find NeuralOperators.jl more applicable.

**Comment by YichengDWu** [comment]
I believe the issue was the same as https://github.com/CarloLucibello/GraphNeuralNetworks.jl/pull/225. So the solution would be switching to the `Flux` branch and rewrite the [layers](https://github.com/YichengDWu/MPPDE.jl/blob/Flux/experiments/models_gnn.jl) in the updated fashion. @utkarsh530

**Comment by utkarsh530** [comment]
cc @cpfpengfei

**Comment by cpfpengfei** [comment]
thanks!

**Pull request merged**
